import "./globals.css";
import main from "./scss/main.module.scss";
import NavBar from "./tc-nav-bar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={main}>
        <div className="tc2021-main tc2021-main-v">
          <NavBar />
          {children}
        </div>
      </body>
    </html>
  );
}
